spring:
  # redis 설정
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:tcp://localhost/~/onboarding-03
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
    generate-ddl: true

logging.level:
  org.hibernate.SQL: debug
  # org.hibernate.type: trace #스프링 부트 2.x, hibernate5
  # org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6